version: '3.7'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_demo
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - sfs

  secure-file-storage-api:
    build:
      context: ./src/middleware
      args:
        - MVN_PROFILES=none
        - SPRING_SERVICE_NAME=secure-file-storage-api
    ports:
      - "8056:8080"
    environment:
      - S3_BASE_PATH=http://localstack:4572
    networks:
      - sfs
networks:
  sfs:
    driver: "bridge"