server:
  port: ${SERVER_PORT:8080}
spring:
  servlet:
    multipart:
      maxFileSize: 30MB
      maxRequestSize: 30MB
aws:
  access:
    key:
      id: ${AWS_S3_ACCESS_KEY:123}
      secret: ${AWS_S3_SECRET_KEY:xyz}
  region: ${AWS_S3_REGION:us-east-2}
  s3:
    bucket: ${AWS_S3_BUCKET_NAME:demo-bucket}
allowed:
  origins: ${ALLOWED_ORIGINS:http://localhost:3000}
