name: build

on: [push]

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        node: ["12"]
    name: test/node ${{ matrix.node }}/${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}
      - run: npm install -g yarn
        working-directory: src/frontend
      - run: yarn install
        working-directory: src/frontend
      - run: yarn build
        working-directory: src/frontend
      - run: yarn test
        working-directory: src/frontend
  coverage:
    needs: [test]
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "12"
      - run: npm install -g yarn
        working-directory: src/frontend
      - run: yarn install
        working-directory: src/frontend
      - run: yarn build
        working-directory: src/frontend
      - uses: paambaati/codeclimate-action@v2.6.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
          coverageCommand: yarn coverage
